### ISSUE TITLE
pip install dllogger not working

### ISSUE THREAD

**Issue by multinucliated** [NVIDIA/dllogger#1]
I was trying to pip install dllogger , but it is not working.

ERROR: Could not find a version that satisfies the requirement dllogger (from versions: none)
ERROR: No matching distribution found for dllogger

**Comment by Fercho120** [comment]
Same issue, I'll try to add it to the repo it uses manually on local

**Comment by Fercho120** [comment]
Solved! Just need to use the supported URL scheme for pip installs from git:
`pip install git+https://github.com/NVIDIA/dllogger.git`

**Comment by multinucliated** [comment]
I'll try again , On that day I tried with this too ! But I'll let you know soon ! if its working or not ?
Thanks for this !!

**Comment by Fercho120** [comment]
It's working in my system, however I must tell you I'm using conda as package manager so in order to install this repo I went to my conda environment binaries folder and there I ran `pip install git+https://github.com/NVIDIA/dllogger.git`
Maybe your issue is something similar

**Comment by akutuzov** [comment]
Is it possible to publish this module on Pypi as a proper Python module?
Or at least provide .tar.gz release archives here on Github?

The current  state of things (that dllogger can only be installed from git) seriously limits its usage, especially in large HPC clusters, where it can be difficult to use an exotic installation method.

**Comment by nikolovn79** [comment]
There is also DNS issue when it is installed by building a Docker image. To avoid DNS with Docker image use

RUN echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null \
    && pip install -e git+https://github.com/NVIDIA/dllogger.git#egg=dllogger

**Comment by gugarosa** [comment]
> Is it possible to publish dllogger on Pypi as a proper Python module? Or at least provide .tar.gz release archives here on Github?
> 
> The current state of things (that dllogger can only be installed from git) seriously limits its usage, especially in large HPC clusters, where it can be difficult to use an exotic installation method.

+1 vote to distribute to PyPI. I have done a workaround and created an `nv_dllogger` package because its current installation method does not work with both pip and setuptools.

**Comment by saeedmaktek** [comment]
this command worked on canda env 
pip install git+https://github.com/NVIDIA/dllogger.git

please use it instead of pip install dllogger

**Comment by jan-golda** [comment]
We currently support [installation](https://github.com/NVIDIA/dllogger#installation) only by `pip install git+https://github.com/NVIDIA/dllogger.git` which should work in most environments.

Feel free to open an issue with details if you encounter problems with it.
