### ISSUE TITLE
Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by decortja** [NVIDIA/dllogger#8]
Hello,

I'm getting this error when trying to install dllogger with both the `pip install git+https://github.com/NVIDIA/dllogger#egg=dllogger
` and `pip install git+https://github.com/NVIDIA/dllogger` commands. Any experience/suggestions to troubleshoot? Thanks.

```
pip install git+https://github.com/NVIDIA/dllogger#egg=dllogger
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting dllogger
  Cloning https://github.com/NVIDIA/dllogger to /tmp/pip-install-ih_1pkem/dllogger_6ceb8d6203ba49c3be0e35fa1f31e79b
  Running command git clone --quiet https://github.com/NVIDIA/dllogger /tmp/pip-install-ih_1pkem/dllogger_6ceb8d6203ba49c3be0e35fa1f31e79b
  warning: templates not found /blue/meilerlab/apps/Linux2/x86_64/git/1.8.1/share/git-core/templates
  fatal: Unable to find remote helper for 'https'
  error: subprocess-exited-with-error
  
  × git clone --quiet https://github.com/NVIDIA/dllogger /tmp/pip-install-ih_1pkem/dllogger_6ceb8d6203ba49c3be0e35fa1f31e79b did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet https://github.com/NVIDIA/dllogger /tmp/pip-install-ih_1pkem/dllogger_6ceb8d6203ba49c3be0e35fa1f31e79b did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by decortja** [comment]
Still not working, but some updates:
per Stack suggestions, I...
- installed curl. No help.
- used git:// , no help/didn't work

I am able to `git clone` the URL fine; I just can't actually install it.

**Comment by jan-golda** [comment]
Hi @decortja!

Which operating system (version?) are you using? Does this happen inside a docker container?  
I know some people encountered issues after switching to docker images based on Ubuntu 22.04, are you using it?

In the meantime you can try the following workaround:
```
git clone https://github.com/NVIDIA/dllogger
pip install ./dllogger
```

**Comment by decortja** [comment]
Interesting - I'm on CentOS7. That error did not occur in a docker container, but I didn't try. Your workaround worked great, really appreciate it.

**Comment by jan-golda** [comment]
This looks like a host-specific issue, probably more related to the OS or Pip. So, I'm closing this issue.

If you, or anyone else reencounters it please let us know.
